### ISSUE TITLE
List of all Leagues

### ISSUE THREAD

**Issue by nickhetland** [StaplePuck/StaplePuck.Frontend.Main#2]
Need a view to show all the leagues (probably separate by sport).
The leagues might need to be grouped by season.
Up to you on how you want to show this. But we need to be able to link to each league.

Query:
query QueryName {
  seasons {
    id
    fullName
    leagues {
      id
      name
      description
    }
  }
}

If you want more info like number of teams. we can probably add nested fields to the query and do a count

**Comment by jdistel83** [comment]
All the leagues pull in and populate a grid table. The League name and Sport columns are sortable. Can add filtering/grouping in phase 2 along with additional CSS cleanup.
